In [1]:
# Testing out symmetrizing and adding transpose of two csr matrices from knn

In [2]:
from sklearn.neighbors import NearestNeighbors
import numpy as np
import scipy.sparse as sps

### generate data and squared distance matrix

In [3]:
data = np.random.rand(2, 5)
print(data)
diffs = data.T[np.newaxis, ...] - data.T[:, np.newaxis, ...]
sqdists = np.sum(diffs**2, axis=-1)
print(sqdists)

[[0.48496023 0.63784343 0.28723871 0.02384442 0.9903322 ]
 [0.4419644  0.92757572 0.80445199 0.1319389  0.52459727]]
[[0.         0.25919162 0.17049105 0.3087436  0.26222901]
 [0.25919162 0.         0.13808312 1.01003272 0.28663996]
 [0.17049105 0.13808312 0.         0.5216504  0.57265912]
 [0.3087436  1.01003272 0.5216504  0.         1.08827921]
 [0.26222901 0.28663996 0.57265912 1.08827921 0.        ]]


### Create nearest neighbor graph

In [4]:
neigh = NearestNeighbors(n_neighbors=3, metric='precomputed')
neigh.fit(sqdists)
knn_sqdists = neigh.kneighbors_graph(sqdists, mode='connectivity')

print("knn matrix:")
print(knn_sqdists.toarray())

K = knn_sqdists
K.data = np.exp(knn_sqdists.data / 0.1)
print("Kernel matrix")
print(K.toarray())

knn matrix:
[[0.         0.25919162 0.17049105 0.         0.        ]
 [0.25919162 0.         0.13808312 0.         0.        ]
 [0.17049105 0.13808312 0.         0.         0.        ]
 [0.3087436  0.         0.5216504  0.         0.        ]
 [0.26222901 0.28663996 0.         0.         0.        ]]
Kernel matrix
[[  1.          13.35533883   5.5008935    0.           0.        ]
 [ 13.35533883   1.           3.97820707   0.           0.        ]
 [  5.5008935    3.97820707   1.           0.           0.        ]
 [ 21.92080119   0.         184.28877958   1.           0.        ]
 [ 13.76721621  17.57363235   0.           0.           1.        ]]


In [14]:
Ktranspose = K.T
K.T.sort_indices()

symm1 = 0.5*(K + K.T)
print(symm1.has_sorted_indices)
#print(symm1)
#symm1.sort_indices()
#print("   ")
print(symm1.toarray())



symm2 = K
symm3 = K.T
symm3.sort_indices
symm2.data = 0.5*(symm2.data + symm3.data)
print(symm2.toarray())

print(symm2.data)
print(symm3.data)

True
[[ 1.         13.35533883  5.5008935  10.9604006   6.88360811]
 [13.35533883  1.          3.97820707  0.          8.78681617]
 [ 5.5008935   3.97820707  1.         92.14438979  0.        ]
 [10.9604006   0.         92.14438979  1.          0.        ]
 [ 6.88360811  8.78681617  0.          0.          1.        ]]
[[  1.          13.35533883   5.5008935    0.           0.        ]
 [ 13.35533883   1.           3.97820707   0.           0.        ]
 [  5.5008935    3.97820707   1.           0.           0.        ]
 [ 21.92080119   0.         184.28877958   1.           0.        ]
 [ 13.76721621  17.57363235   0.           0.           1.        ]]
[  1.          13.35533883   5.5008935   13.35533883   1.
   3.97820707   5.5008935    3.97820707   1.          21.92080119
 184.28877958   1.          13.76721621  17.57363235   1.        ]
[  1.          13.35533883   5.5008935   13.35533883   1.
   3.97820707   5.5008935    3.97820707   1.          21.92080119
 184.28877958   1.     